### ISSUE TITLE
 :unneeded is deprecated

### ISSUE THREAD

**Issue by hrodrig** [hidetatz/kubecolor#81] opened 2021-10-29 15:55 UTC
After update to Monterey, I have this issue:

```
% brew upgrade kubecolor
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the dty1er/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/dty1er/homebrew-tap/Formula/kubecolor.rb:9
```

**Comment by pjwalstrom** [comment] 2021-11-02 08:15
Duplicate of https://github.com/dty1er/homebrew-tap/issues/1

**Closed** 2021-12-21 09:18 UTC
