### ISSUE TITLE
install fail on homebrew on mac

### ISSUE THREAD

**Issue by adrian-agot** [hidetatz/kubecolor#104] opened 2022-06-30 19:08 UTC
brew install hidetatz/tap/kubecolor
==> Tapping hidetatz/tap
Cloning into '/usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 12), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 7.89 KiB | 336.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/hidetatz/homebrew-tap/Formula/kubecolor.rb
kubecolor: wrong number of arguments (given 1, expected 0)
Error: Cannot tap hidetatz/tap: invalid syntax in tap!

**Comment by vikas027** [comment] 2022-07-01 15:18
Hey @adrian-agot ,
This is duplicate of https://github.com/hidetatz/kubecolor/issues/90

The current workaround is `brew install jjuarez/homebrew-tap-1/kubecolor`

**Comment by n-hebert** [comment] 2022-07-13 12:53
Same result on linux, filed over here: https://github.com/hidetatz/homebrew-tap/issues/5

**Comment by marandalucas** [comment] 2022-09-22 08:16
Please, update the documentation for the workaround. Thank you!

**Comment by hidetatz** [comment] 2022-12-31 03:33
This issue is now fixed. Please reopen if it still happens.

**Closed by hidetatz** 2022-12-31 03:33 UTC
